
language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
    - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
jdk:
  - oraclejdk8

services:
  - mysql

script:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 


before_install:
    - mysql -e 'CREATE DATABASE mysql_db;'

deploy:
  provider: openshift
  user: "crm.admin2@lxisoft.com"
  password: "rbs123" # can be encrypted
  domain: "remoterbs"
  app: remoterbs
  
