
language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
    - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
jdk:
  - oraclejdk8

services:
  - mysql

script:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 


before_install:
    - mysql -e 'CREATE DATABASE mysql_db;'

production:
    type: deploy
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - git config --global push.default matching
        - dpl --provider=openshift --user=$OPENSHIFT_USER --password=$OPENSHIFT_PASS --domain=remoterbs --app=web
    only:
        - tags
    environment: production