spring:
 datasource:
  username : root
  password : admin
  url : "jdbc:mysql://localhost:3306/lenus"
 http:
  multipart:
   max-file-size : 124kb
 
 jpa:
  show-sql : true
  hibernate:
   ddl-auto : update
   naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
 properties:
  hibernate:
   dialect : org.hibernate.dialect.MySQL5Dialect
 
